### ISSUE TITLE
No visible way to provide proxy settings

### ISSUE THREAD

**Issue by devbeard** [noobot/SlackConnector#10]
I don't see a way to provide proxy settings for the connector

**Comment by Workshop2** [comment]
Hello,

I looks like we could add it quite easily. When I find some time I will add it.

Ref: https://github.com/dehealy/websocket-sharp#connecting-through-the-http-proxy-server

**Comment by Workshop2** [comment]
Hey @devbeard, I have added in the support for proxies like you requested. Please get latest from nuget to see it (**version 3.0.5928.43140**) and let me know how you get on.

https://www.nuget.org/packages/SlackConnector/3.0.5928.43140

**Comment by Workshop2** [comment]
@devbeard - I am closing this as I assume it works. Please re-open if there are problems.
