### ISSUE TITLE
Channel Creation Event

### ISSUE THREAD

**Issue by Rumple-Phillip** [noobot/SlackConnector#12]
Am curious if this plugin will allow for the detection of channel_created  events from Slack?  This way we can invite the bot the created channel if it matches what we need? 

Ergo, we want our bot in any channel that's created for our live chat channels, so we would ideally: 
- Listen for the channel_created  event
- Invite the bot to the new channel using an invite token from one of our admins
- Bot would join room, and be ready to listen to commands. 

Just curious if this would be possible with SlackConenctor?

**Comment by Workshop2** [comment]
Current the bot doesn't purposely emit a channel created event. It would be very easy to build into the slack connector as it's just a type of message received from the web socket

**Comment by Workshop2** [comment]
@Rumple-Phillip  This is now released https://github.com/noobot/SlackConnector/releases/tag/4.1.52
