### ISSUE TITLE
message received

### ISSUE THREAD

**Issue by koenvzeijl** [noobot/SlackConnector#13]
Hello i am new to making slack bots,  now is my question do you get the messages from slack and where is this saved?

i can already send messages but just sending is useless when you didn't know what you got.

**Comment by Workshop2** [comment]
Hello @koenvzeijl,

There is an event that is raised: https://github.com/noobot/SlackConnector/blob/master/src/SlackConnector/ISlackConnection.cs#L78

```
ISlackConnector connector = new SlackConnector.SlackConnector();
ISlackConnection connection = await connector.Connect(slackKey);
connection.OnMessageReceived += MessageReceived;
```
