### ISSUE TITLE
SlackConnector doesn't seem to respect proxy settings. Connection through NTLM proxy fails. 

### ISSUE THREAD

**Issue by ghost** [noobot/SlackConnector#17]
I'm trying to run Noobot "out of the box" but I cannot get a connection to go through our proxy server. 
I have configured

```
  <system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
      <proxy usesystemdefault="True"/>
    </defaultProxy>
  </system.net>
```

in App.config in Noobot but I still get a connection error. 
Running Fiddler I can see that there is a request to https://slack.com/api/rtm.start which returns a json object, so that works fine. However initiating the WebSocket connection afterwards fails because it doesn't try to connect through the configured proxy. The request never shows up in Fiddler, and I get the well-known "No connection could be made because the target machine actively refused it".

**Comment by ghost** [comment]
Actually on further investigation this looks more like a problem in WebSocket-Sharp. Closing.

**Comment by Itsey** [comment]
@graffen did you manage to get this resolved?  the slack connector isnt much use without that connectivity and even though the issue is in the websockets layer the issue there was closed without resolution.
