### ISSUE TITLE
Any implemented examples ?

### ISSUE THREAD

**Issue by kublaikhan1** [noobot/SlackConnector#18]

**Comment by Workshop2** [comment]
Hey @hamadkh - I built this library for Noobot, here try this: 
https://github.com/noobot/noobot/blob/master/src/Noobot.Core/NoobotCore.cs#L43

**Comment by Workshop2** [comment]
Also, @hamadkh you need to invite the bot into channels you want it to react to (just like a person)

**Comment by Workshop2** [comment]
Also, @hamadkh you need to invite the bot into channels you want it to react to (just like a person)
