### ISSUE TITLE
total newbie

### ISSUE THREAD

**Issue by vboilay** [noobot/SlackConnector#23]
Hi,
I got the package from nuGet within VS.
I first used the few lines from your Usage section
looks like connection.OnConnectionStatusChanged does not exists anymore. 

Then about the slackKey in
ISlackConnection connection = await connector.Connect(slackKey);

not sure what I should put there. Is that the token generated by slack token generator ?
or ? 

Thx

**Comment by Workshop2** [comment]
Hello,

Thanks for pointing out the readme is wrong, I have updated it to use `OnDisconnect`.

You need to register a bot on slack at the following location to get a slack key: https://my.slack.com/services/new/bot

Thanks,
Simon

**Comment by vboilay** [comment]
Thx for the quick answer.  I appreciate.
I will give a go to that and let you know.
I will write down all the steps I will go thru so that you will have a walk
thru for total newbies.

**Comment by Workshop2** [comment]
Thanks @vboilay - if it helps here is how I use it in Noobot https://github.com/noobot/noobot/blob/master/src/Noobot.Core/NoobotCore.cs#L41

**Comment by Workshop2** [comment]
Hey @vboilay I am going to close this issue due to inactivity.

Feel free to re-open if you need more help.
