### ISSUE TITLE
Is there a "mrkdwn" or "mrkdwnin" field available?

### ISSUE THREAD

**Issue by StingyJack** [noobot/SlackConnector#26]
For attachments, there is a property that can be used to control what gets formatted. I may just be thick headed and missing it, can you let me know if there is something existing that controls this?

//        "mrkdwn_in": ["text", "pretext", "fields"],

**Comment by StingyJack** [comment]
Pull request submitted to add this to attachments (its on by default for a message but not attachments).

**Comment by Workshop2** [comment]
This has been release: https://www.nuget.org/packages/SlackConnector/3.1.116
