### ISSUE TITLE
Unable to parse different types of messages

### ISSUE THREAD

**Issue by Workshop2** [noobot/SlackConnector#3]
{"type":"im_created","user":"U0DKUTE0L","channel":{"id":"D0EEU58RL","is_im":true,"user":"U0DKUTE0L","created":1447411860,"last_read":"0000000000.000000","latest":null,"unread_count":0,"unread_count_display":0,"is_open":false}}

**Comment by 10der** [comment]
issue is here:

```
                    message.Channel = WebUtility.HtmlDecode(message.Channel);
                    message.User = WebUtility.HtmlDecode(message.User);
                    message.Text = WebUtility.HtmlDecode(message.Text);
                    message.Team = WebUtility.HtmlDecode(message.Team);
                    message.RawData = json;
```

author not check message.Channel message.User message.Text message.Team on null
and WebUtility.HtmlDecode( throw exception: 

System.ArgumentNullException: Argument cannot be null.
Parameter name: s
  at System.Net.HttpUtility.HtmlDecode (System.String s) [0x00000] in <filename unknown>:0
  at System.Net.WebUtility.HtmlDecode (System.String value) [0x00000] in <filename unknown>
  at SlackConnector.Connections.Sockets.Messages.Inbound.MessageInterpreter.InterpretMessag                        son) [0x00000] in <filename unknown>:0

**Comment by Workshop2** [comment]
Already fixed
