### ISSUE TITLE
MissingMethodException on version 3.1.176.0

### ISSUE THREAD

**Issue by okfro** [noobot/SlackConnector#44]
Furl v: 2.3
SlackConnector v: 3.1.176.0

I init my connection like so:

```
ISlackConnector connector = new SlackConnector.SlackConnector();
_connection = connector.Connect( $"{someValidApiKey}" ).Result;
```

Line 2 fails with a:

```
System.AggregateException: 'One or more errors occurred.'
Inner Exception:
MissingMethodException: Method not found: 'Flurl.Url Flurl.Url.SetQueryParam(System.String, System.Object)'.
```

It would appear this is a fault with Furl and not with SlackConnector. For now, I'll try reverting to previous versions of SlackConnector until I find one that lines up to a Furl version that still works.

**Comment by okfro** [comment]
So downgrading to SlackConnector v: 3.1.151.0 resolves the issue. Furl remains at v: 2.3 after the NuGet downgrade.

**Comment by Workshop2** [comment]
SlackConnector 3.1.201 has been released - can you see if this fixes the issue? _(I have simply updated the dependency)_ @crfroehlich
