### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by SRT5752** [noobot/SlackConnector#5]
Appreciating this library. Initially found three potential issues:
- I can not get attachments to work. The message text goes through though, no exception thrown
- The NuGet package does not install completely under Mono due to framework restrictions
- Logging interface or option to disable logging to console

**Comment by Workshop2** [comment]
Hello, thanks for the feedback.

I will look into these issues when I get a moment.

With regards to the mono issue (I haven't used it before) - what errors did you get and do yo have any tips so I can get up and running quickly?

Thanks,
Simon

**Comment by SRT5752** [comment]
My best guess at a minimal change is to switch target framework version from 4.5.2 to 4.5. I tried this,  created a simple nuspec, it seems to install correctly from a local package source.

**Comment by SRT5752** [comment]
I had a look at the other things while I was at it.
- Typo: "attachment" should be  "attachments"
- The WebSocket library default is debug logging

``` c#
request.AddParameter("attachments", JsonConvert.SerializeObject(attachments));
```

``` c#
_webSocket.Log.Level = LogLevel.Warn;
```

**Comment by Workshop2** [comment]
Ah, nice work. I will try and get this sorted tonight. Feel free to submit a pull request if you have a working copy

**Comment by Workshop2** [comment]
It's just been submitted (might be a few minutes until you can install it) but this version should contain all of the fixes:
https://www.nuget.org/packages/SlackConnector/3.0.5811.41364

Let me know how Mono goes, not sure if there are other things I need to do?

**Comment by SRT5752** [comment]
Everything seems to install properly. I can now post messages with attachments and also no annoying debug logs :)

Thanks!

**Comment by Workshop2** [comment]
Glad to have helped. Please submit any other pull requests/issues/features when you find them.
