### ISSUE TITLE
Interactive Message 

### ISSUE THREAD

**Issue by m23tran** [noobot/SlackConnector#58]
Hi just wondering is it possible to have some interactive messages ? Would be a great feature to have. 

https://api.slack.com/docs/message-buttons

**Comment by m23tran** [comment]
I believe it's available, it's called attachments. Sorry for misunderstanding

**Comment by m23tran** [comment]
@Workshop2 Hi, complete newbie here. Any tips on using interactive messages? I was successfully able to attach them but now I'm wondering how do I implement the call back? When a button is clicked, i'm presented with `Darn – that didn’t work. Only Slack Apps can add interactive elements to messages. Manage your apps here: https://api.slack.com/apps/`

**Comment by Workshop2** [comment]
Looks like you need to specify a URL endpoint for the buttons to work.

In my head you could host your bot in a web app, and then you can receive messages from the web side and the slack rtm side.

**Comment by Workshop2** [comment]
https://api.slack.com/interactive-messages#readying_app
