### ISSUE TITLE
Error using Interactive Messages

### ISSUE THREAD

**Issue by m23tran** [noobot/SlackConnector#59]
My bot will come online and OnMessageReceive will trigger. When sending interactive messages with request URL setup, i'm given this error 

https://i.imgur.com/JHAViaC.png  
![image](https://user-images.githubusercontent.com/6067320/30784051-67e8a244-a102-11e7-90b2-c87145e35956.png)

@Workshop2  any thoughts?

**Comment by Workshop2** [comment]
That error message makes it sound like only apps can send interactive messages. 

https://api.slack.com/bot-users

According to this you can wrap a bot up in a slack app:
>>>Make messages interactive with buttons
Bot users wrapped in Slack apps can attach buttons to messages. These buttons trigger actions on your servers, allowing your bot to perform distinct tasks and incrementally alter messages.

**Comment by m23tran** [comment]
Ahh okay. If I attach it to a slack app it is working instead of a slack user.

**Comment by Workshop2** [comment]
Good to know, do you have a open source project to show it working? 👍
