### ISSUE TITLE
Missing Message Type causing exception when connecting

### ISSUE THREAD

**Issue by liqdfire** [noobot/SlackConnector#60]
I am using Noobot nuget package 3.1.35 and Slack Connector nuget package 4.1.16

When my client connects I am receiving an exception "'Requested value 'hello' was not found.'"

The message received is here: https://api.slack.com/events/hello

The MessageInterpreter is erroneously assuming any message that it receives that is not in the enum is a chat message and tries to deserialize it as such. That feels like a pretty big point of fragility, especially given that the chat message has a well defined type.

**Comment by Workshop2** [comment]
Hello @liqdfire,

The code that handles mappings of JSON to POCO is wrapped up in a try-catch so it should be safe. However, I do agree that this could cause issues and I will submit a change to ignore unknown message types.

**Comment by Workshop2** [comment]
Released in 4.1.21
