### ISSUE TITLE
OnMessageReceived not triggered by Webhook

### ISSUE THREAD

**Issue by m23tran** [noobot/SlackConnector#61]
Hi, my current setup is as followed. I have 2 projects, one console app for the bot purposes (onmessagereceived, onuserjoined, ondisconnected, onreconnect) and a asp.net mvc app to capture post request sent when an interactive messages are clicked. I send a basic response back to the chat but it seems the bot doesn't trigger onmessagereceived when that happens.

**Comment by Workshop2** [comment]
Are you authenticated as the same bot in both apps? If so it wont receive messages from itself

**Comment by m23tran** [comment]
I've tried with another bot as well. Maybe because I'm sending the reply as a webhook?

**Comment by Workshop2** [comment]
I am not sure what to suggest. Under the hood we use the API end points to send messages:
https://github.com/noobot/SlackConnector/blob/master/src/SlackConnector/Connections/Clients/Chat/FlurlChatClient.cs#L22
