### ISSUE TITLE
SlackConnector and Noobot

### ISSUE THREAD

**Issue by wh1337** [noobot/SlackConnector#67]
As I’m trying to figure out the scale and scope of this project and library for Slack I felt it was time to reach out to you lol. 

Noobot works with The SlackConnector correct? Or are the entire 2 project separate? I plan to contribute some improvements I have made as I finalize them but just want to make sure my understand is up to speed on the layout.

**Comment by Workshop2** [comment]
Greetings @williamhodges 

SlackConnector powers Noobot - if you need to make changes to both you will need to iterate on them separately. SlackConnector is meant to be usage agnostic (not just for Noobot, however, it was originally built for that).
