### ISSUE TITLE
Accessing user name instead of user

### ISSUE THREAD

**Issue by m23tran** [noobot/SlackConnector#68]
Hi,

Was wondering is there a way to access the username that is set by the user. At the moment the Username is always set to whatever the email address is minus the @ + domain.

As you can see, i digged into GetMessageUser and this is what the UserCache Contains

![image](https://user-images.githubusercontent.com/6067320/33359449-d24d59cc-d49c-11e7-8f18-11bf33308da8.png)

**Comment by Workshop2** [comment]
Hello, I am unable to replicate this. Are their username and email the same?

![image](https://user-images.githubusercontent.com/1476513/34419285-d610ac06-ebfa-11e7-8506-77bf7855f0cc.png)
