### ISSUE TITLE
The Write method cannot be called when another write operation is pending

### ISSUE THREAD

**Issue by okfro** [noobot/SlackConnector#80]
I cannot connect to Slack with this error, usually in full:

```
NotSupportedException:  The Write method cannot be called when another write operation is pending.
```

Which seems to be well documented, but somewhat old in other deps. See:

* https://github.com/1iveowl/WebsocketClientLite.PCL/issues/32
* https://github.com/1iveowl/SocketLite.PCL/issues/5
* https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/417 (not directly related but useful)

**Comment by Workshop2** [comment]
@crfroehlich can you put together a GitHub repo with a minimum via project replicating the error for review.

It would help to debugging.

**Comment by okfro** [comment]
You can repro the issue just by running the unit tests. All I did was pull down this repo and drop in my bot token for `"slack:apiToken"` in `config.json`. Some tests pass; most fail with this error. You *can* get a few specific tests that have failed to pass if you run them one at a time.

The error/behavior is the same in the unit tests regardless of the WebsocketClientLite version used (anywhere between 5.0 - 6.* latest), and the error is the same as when I consume SlackConnector (in my own app) via the published NuGet package.

**Comment by Workshop2** [comment]
The websocket library has been replaced, and this issue seems to have been solved
