### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by MonkAlex** [noobot/SlackConnector#84]
> On February 19, 2020, Slack will end support for TLS versions 1.0 and 1.1. We've identified that one or more of your Slack apps are impacted by this change. If you don't upgrade your app to TLS 1.2, requests sent to any Slack endpoint will fail.
> You must update your Slack app before February 21, 2020. Please verify which of your Slack apps are affected: https://api.slack.com/unsafe-tls-deprecation

In code i just use
```
      var client = new SlackConnector.SlackConnector();
      connect = await client.Connect(token);
```

have u apps in https://api.slack.com/unsafe-tls-deprecation or its only my problem?

**Comment by Workshop2** [comment]
Thanks @MonkAlex - I need to investigate how nuget libraries can handle this as I believe the TLS handshake behaviour is handled in the execution context/host (e.g. console app)

**Comment by Workshop2** [comment]
@MonkAlex as a stop gap, can you upgrade your app to be .NET 4.6.1 or above?

>A solution for was to upgrade my application to the latest .NET framework: 4.6.1. In this framework version TLS 1.2 is a default cryptographic standard.

**Comment by MonkAlex** [comment]
@Workshop2 my app already 4.6.1, i try to update version to 4.7.2, its not help -- slack show my app on link.

**Comment by MonkAlex** [comment]
Set ```ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;``` on app start, but slack show my app on link...

No idea, how to fix it.

**Comment by MonkAlex** [comment]
Hmmm, nothing changed, but slack write on page now:
`No action needed — we weren’t able to detect any legacy TLS usage.`

**Comment by Workshop2** [comment]
Good I know. I was able to replicate the bug.
