### ISSUE TITLE
Getting "invalid_auth" error once I try to connect to slack but via Postman using App-Level Token it's working !

### ISSUE THREAD

**Issue by YHSX88** [noobot/SlackConnector#95]

**Comment by YHSX88** [comment]
To add more info, I managed to do the call via Postman **but still getting error in my script**:
![image](https://user-images.githubusercontent.com/16823745/109347403-cd8fdc80-787b-11eb-96d9-a6df1281f37e.png)

Any help is welcomed. Thank you !

**Comment by Invectys** [comment]
what was the problem ?

**Comment by Invectys** [comment]
It works with BOTS not APPS
https://my.slack.com/services/new/bot - legacy bots
