### ISSUE TITLE
Error occured while posting message 'method_deprecated'

### ISSUE THREAD

**Issue by MonkAlex** [noobot/SlackConnector#96]
Error occured while posting message 'method_deprecated'
SlackConnector.Exceptions.CommunicationException

SlackConnector.Connections.Clients.ResponseVerifier.VerifyResponse(StandardResponse response)
SlackConnector.Connections.Clients.Channel.FlurlChannelClient.<GetChannels>d__17.MoveNext()

https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by Workshop2** [comment]
Fixed in v5.1.11
